# Generated by Django 3.2.20 on 2023-08-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='time',
            new_name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='difficulty',
        ),
    ]
